from __future__ import annotations

import os
import re
from datetime import date
from pathlib import Path
from typing import Any, Literal

import yaml

from autofly.config import AppConfig
from autofly.errors import ConfigError


def parse_iata_list(value: str, field: str) -> list[str]:
    codes = [item.strip().upper() for item in value.split(",") if item.strip()]
    if not codes:
        raise ConfigError(f"{field} must contain at least one IATA code")
    invalid = [code for code in codes if not re.fullmatch(r"[A-Z]{3}", code)]
    if invalid:
        raise ConfigError(f"Invalid {field} IATA code(s): {', '.join(invalid)}")
    if len(codes) != len(set(codes)):
        raise ConfigError(f"{field} must not contain duplicate codes")
    return codes


def build_setup_config(
    *,
    origins: list[str],
    destinations: list[str],
    date_mode: Literal["exact", "range", "rolling"],
    date_values: dict[str, Any],
    currency: str,
    maximum_price: float,
    timezone: str,
    telegram_enabled: bool,
    docker: bool,
    config_path: Path,
) -> AppConfig:
    routes = len(origins) * len(destinations)
    query_budget = max(50, routes * (1 if date_mode == "exact" else 6))
    state_dir = Path("/var/lib/autofly") if docker else config_path.resolve().parent / "data"
    watch_id = f"{origins[0].lower()}-{destinations[0].lower()}"
    raw = {
        "version": 1,
        "database": {"path": str(state_dir / "autofly.db")},
        "scheduler": {
            "interval_hours": 6,
            "jitter_minutes": 10,
            "timezone": timezone,
            "max_queries_per_cycle": query_budget,
            "lock_path": str(state_dir / "autofly.lock"),
        },
        "sources": {
            "flight_goat": {
                "enabled": True,
                "command": "flight-goat-pp-cli",
                "pace_seconds": 5,
                "expected_version": "2026.8.1",
            }
        },
        "notifications": {
            "telegram": {"enabled": telegram_enabled},
            "webhook": {"enabled": False},
        },
        "watches": [
            {
                "id": watch_id,
                "enabled": True,
                "origins": origins,
                "destinations": destinations,
                "trip": {"type": "one_way", "adults": 1, "cabin": "economy"},
                "dates": {"mode": date_mode, **date_values},
                "deal": {
                    "currency": currency.upper(),
                    "maximum_price": maximum_price,
                    "max_stops": 1,
                    "allow_self_transfer": False,
                },
                "notifications": {"cooldown_hours": 24},
            }
        ],
    }
    return AppConfig.model_validate(raw)


def write_setup_files(
    config: AppConfig,
    *,
    config_path: Path,
    env_path: Path,
    telegram_token: str | None,
    telegram_chat_id: str | None,
    docker: bool,
) -> None:
    existing = [str(path) for path in (config_path, env_path) if path.exists()]
    if existing:
        raise ConfigError(f"Refusing to overwrite existing file(s): {', '.join(existing)}")
    for name, value in (
        ("Telegram bot token", telegram_token),
        ("Telegram chat ID", telegram_chat_id),
    ):
        if value is not None and any(character in value for character in "\r\n\0"):
            raise ConfigError(f"{name} contains an invalid control character")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        yaml.safe_dump(config.model_dump(by_alias=True, mode="json"), sort_keys=False),
        encoding="utf-8",
    )
    config_value = "/etc/autofly/config.yaml" if docker else str(config_path.resolve())
    lines = [
        "# Generated by autofly setup. Keep this file private.",
        f"AUTOFLY_CONFIG={config_value}",
        f"AUTOFLY_MAX_QUERIES_PER_CYCLE={config.scheduler.max_queries_per_cycle}",
        "AUTOFLY_FLIGHT_GOAT_COMMAND=flight-goat-pp-cli",
    ]
    if telegram_token is not None and telegram_chat_id is not None:
        lines.extend(
            [
                f"TELEGRAM_BOT_TOKEN={telegram_token}",
                f"TELEGRAM_CHAT_ID={telegram_chat_id}",
            ]
        )
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if os.name != "nt":
        env_path.chmod(0o600)


def parse_iso_date(value: str, field: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise ConfigError(f"{field} must use YYYY-MM-DD") from exc
